### ISSUE TITLE
Rolladensteuerung

### ISSUE THREAD

**Issue by Pitastic** [Daumen-Hoch-AG/PiHomie#10]
...ich muss auch noch einen Rolladengurt rausreißen, weil die Küche sonst nicht passt.

Also wird gleich automatisiert 😃 

Da wir/ich ja bei den Heizkörpern beim anderen Issue #1 in Richtung eq3 gehe und zWave etwas zu teurer ist, schaue ich dazu hier auch erstmal in der Richtung. Die Lösungen könnten untereinander interessant sein und unser Projekt schon in eine Richtung formen 😏

**Comment by Pitastic** [comment]
Gekauft wird ein Rolladenmotor der über einen Wandschalter bedienbar ist. Der Wandschalter wird dann mit einer SmartHome Lösung ersetzt um das System ansteuerbar zu machen.

Weil ich bei den Thermostaten ja schon eine kleine Einschränkung gemacht habe beschränke ich mich bei der Suche erstmal auf zwei Standards (sofern sich nicht etwas aufdrängt).

#### Homematic
- <a href='http://www.contronics.de/shop/Rolladensteuerung/HomeMatic-Funk-Rolladenaktor-mit-Tastenaufsatz-1fach.html'>Funk Rolladenaktor mit Tastenaufsatz 1fach (~60 €)</a>
  - auch ohne Schalterabdeckung erhältlich<br>
    <a href='http://www.notebooksbilliger.de/homematic+funk+jalousieaktor+1fach/?nbb=pla.google_&wt_cc2=926-0001_Heimautomatisierung_127873&gclid=CJis_InKvs8CFUESGwodu7QArw'>z.B. bei notebooksbilliger (~55 €)</a>
  - auch als Unterputzmontage hinter bestehenden Tastern (nicht Schaltern) möglich <br><a href='https://www.amazon.de/dp/B001I9ZLME?m=A3JWKAKR8XB7XF&tag=idealode-am-pk-21&ascsubtag=cGVfVzQ65617SzxBLDYNhQ'>fast zum gleichen Preis (~53 €)</a> und ich habe bisher Schalter (keine Taster)

#### zWave
- Unterputz Relais, was mit einem Taster oder Schalter betrieben werden kann oder über zWave geschaltet wird (Schalter müsste ich separat kaufen):
  - <a href='http://www.zwave-shopping.com/de/fenster-rollladen-und-jalousie-steuerung/philio/252-relais-unterputzeinsatz-jalousie.html'>von Philio für ~42 €</a> (sehr wenig verfügbar)
  - fast das gleiche von der größeren Marke inklusive Stromverbrauchsmessung <br><a href='https://www.notebooksbilliger.de/netzwerk/smart+home+netzwerk/z+wave/fibaro+fgr+222+jalousiesteuereinsatz+rolladen+steuerung+rev+02'>Fibaro für ~49 €</a>

_...und das wars wohl auch schon..._

**Comment by janleck** [comment]
Wie ist denn das bei dem Rolladenmotor mit dem Endschalter? Da könnte es ja auch undefinierte Zustände geben. Nicht, dass dir dann die Bude abfackelt weil der heiß läuft, wenn er schon unten ist aber das kluge SmartHome meint es geht noch weiter ??

**Comment by Pitastic** [comment]
Ich suche gerade noch nach einem passenden Motor. Die Guten (einer von denen, den ich kaufen werde) haben eine Abschaltautomatik, wenn ein Endpunkt erreicht ist. Unabhängig vom Schalter kennt der Motor auch die Länge des Fensters und wo oben bzw. unten ist. Ob das dem Smarthome ggf in die Quere kommen könnte müsste man mal sehen, habe ich aber noch nichts von gelesen.

#### zur Entscheidung

Ich schaue mal im Baumarkt nach Schalteraufsätzen. Tendiere aber zum Fibaro, weil es das einfach besser ausgestattete System ist. Und damit hätte ich bei Heizung und Rolladen schon 2 verschiedene Systeme und gebe unserem Projekt einen Sinn 😀

**Comment by Pitastic** [comment]
Es wird der Fibaro
https://www.notebooksbilliger.de/netzwerk/smart+home+netzwerk/z+wave/fibaro+fgr+222+jalousiesteuereinsatz+rolladen+steuerung+rev+02
