### ISSUE TITLE
Razberry generell

### ISSUE THREAD

**Issue by janleck** [Daumen-Hoch-AG/PiHomie#18]
Welchen RaZberry hast du denn jetzt, die erste oder die zweite Variante? 

1: `https://www.cyberport.de/z-wave-plus-modul-fuer-den-raspberry-pi-razberry-zme-raz-eu-5C14-010_8419.html
`
2: `https://www.cyberport.de/razberry2-z-wave-plus-modul-fuer-den-raspberry-pi-eu-version-5C14-07M_8419.html`

**Comment by Pitastic** [comment]
RaZberry2 Z-Wave Plus Modul für den Raspberry Pi EU Version - **49,90 €**
