### ISSUE TITLE
Systemlogger

### ISSUE THREAD

**Issue by Pitastic** [Daumen-Hoch-AG/PiHomie#19]
Instanz für bequemes und aufgeräumtes Loggen nach standard-Locations.

Ich habe unter `modules/services/Logging.py` schon mal angefangen und drei verschiedene Arten festgelegt:

- `Status` (jegliche Kommunikation und Vorgänge ohne Fehler)
- `Error` (jegliche Fehlermeldungen)
- `Info` (optionale Ausgabe, die nicht in `Status` untergehen soll... ?)

**Comment by Pitastic** [comment]
```
if os.path.isdir(logDir):
  pass
else:
  return false
```
Ich checke ob das Log-Verzeichnis vorhanden ist. Muss ich eine Exception auslösen ?

**Comment by janleck** [comment]
Wenn man es ganz Korrekt macht würde ich sogar checken ob man in das Verzeichnis schreiben kann. Auf die schnelle hab ich sowas jetzt gefunden:
os.access('/path/to/folder', os.W_OK) # W_OK is for writing, R_OK for reading, etc.
Und dann halt wenn es nicht so ist eine exception werfen mit aussagekräftigem Text.

Die drei verschiedenen Log-Arten find ich gut, könnte man dann später in einer WEB-UI noch farbig einfärben.

**Comment by Pitastic** [comment]
:+1: 
1. Was ist mit dem Exception Raise ?
2. Ich benutze für den Timestamp jetzt local time (`datetime.datetime.now()`) statt utc time (`datetime.datetime.utcnow()`). zWay neutzt irgendwie auch je nach Oberfläche beides ... lasse es erstmal bei local time, müssen wir mal beobachten

**Comment by Pitastic** [comment]
https://docs.python.org/2/library/os.html#files-and-directories
`os.access()` ist nicht mehr sicher genug.

Wir nehmen:
```
try:
    fp = open("myfile")
except IOError as e:
    if e.errno == errno.EACCES:
        return "some default data"
    # Not a permission error.
    raise
else:
    with fp:
        return fp.read()

**Comment by Pitastic** [comment]
Der Service `Logger` ist im Modul `Systemservices` definiert und wird beim Start instanziiert und an das Objekt `SysSrv['Logger']` angehängt. Das Objekt wird jeder anderen Instanz mit beim Instanziieren übergeben ist so überall verfügbar.

**Comment by Pitastic** [comment]
...alles nochmal anders

**Comment by Pitastic** [comment]
Logging ist mit flask und einer Logging-Instanz umgesetzt. Es wird in verschiedene Log-Datei je nach Config geschrieben !
