### ISSUE TITLE
Projektplan

### ISSUE THREAD

**Issue by Pitastic** [Daumen-Hoch-AG/PiHomie#2]
Fahrplan, Prioritätenliste und Kernfeatures bestimmen.
Github-Features einrichten.

**Comment by janleck** [comment]
#8

**Comment by janleck** [comment]
Objektrelationaler Entwurf der Grundstruktur. Basisklassen für Sensoren und Aktoren, Schnittstellendefinition.

**Comment by Pitastic** [comment]
Eine OOP-Grafik wäre schön :grimacing:

**Comment by Pitastic** [comment]
### Kernfeatures und Prioritäten von Gerätesupport o.ä. :white_check_mark: 
...habe ich über einzelne Issues mit [Support]-Tag gelöst, die wir Milestones und Bearbeiter zuordnen können, um Prioritäten zu verdeutlichen.
Zum planen der Prioritäten gibt es ein Projekt "Prioritätenliste" in dem wir eine Übersicht haben.

### Objektrelationaler Entwurf der Grundstruktur
Was bleibt ist der Entwurf der Objekte und dafür würde ich dieses Issue weiter nutzen.
Kannst du hier einen Eintrag schreiben, in den du immer die JPG-Version deiner Entwurf.pdf einfügst (Eintrag immer editieren). Geht hier sehr angenehm mit Drag und Drop und dann fliegt sowas nicht im Repository rum und man kann es sich besser anschauen.

**Comment by Pitastic** [comment]
Können wir das Issue vielleicht mal abschließen. Also mit einer grob fertigen Version deiner Entwurf.pdf, wo man auch mal was erkennt :stuck_out_tongue_closed_eyes: 
Dann hätten wir nämlich schon einen Meilenstein geschafft :smiley: (machen ja eh schon was anderes...)

**Comment by janleck** [comment]
Es wäre natürlich von Vorteil, wenn wir uns was die Schnittstellen angeht also Methoden etc. zumindest etwas an den Plan halten würden ;-)
![entwurf](https://cloud.githubusercontent.com/assets/11072661/22515760/e29226c2-e8a3-11e6-8b57-fc2e1a17aa3b.jpg)
