### ISSUE TITLE
Python import und OOP

### ISSUE THREAD

**Issue by Pitastic** [Daumen-Hoch-AG/PiHomie#20]
#### 1. Wo findet denn der import statt ?
Sowohl in `DEV.py` was später ja durch ein `main.py` ersetzt werden könnte brauche ich Standardbibliotheken wie `os` oder auch `requests`. Die brauche ich in unseren Modulen aber auch. Werden die dort dann nochmal erneut importiert ?
Das könnte ziemlich viele doppelte Importe geben. Muss das sein ?

#### 2. Methodenaufrufe
Ich habe eine Klasse für das Logging inkl der Methoden erstellt. Sie wird in der `DEV.py` instanziiert. Wenn ich jetzt aber im Modul `RollerShutter.py` diese Instanz zum Protokollieren nutzen möchte, muss ich sie dann extra übergeben ? Kann man die Instanz global machen ? Wenn ja, wie würde ich die denn dann in der Methode von `RollerShutter.py` aufrufen ?

**Comment by janleck** [comment]
**Zu 1.**
Ich weiss nicht wie sich Python da genau verhält, aber eigentlich müssten die Imports ja mit vereerbt werden, also müssten es theoretisch immer weniger Imports werden um so weiter sich die Klasse spezialisiert. Wenn man das also geschickt anstellt gibt es kaum doppelte Imports. Denn alle Klassen von einer Datei abhängig zu machen wegen den Imports find ich irgendwie wenig elegant, weiss aber nicht was da in Python als "goldener" Weg gilt.

**Zu 2.**
Es gibt denke ich mehrere Möglichkeiten, die eine wäre eine statische Klasse, die Global ist. (Sofern Python das zulässt) Dann könnte man eine Art Service an die Geräte weiterreiche - nicht elegant. Eine weitere Möglichkeit wäre noch einfach immer wieder eine neue Instanz zu erstellen, spricht ja eigentlich nix dagegen, schreibt ja eh nur ans ende einer Datei und holt sich evtl noch die Pfade aus irgendeiner Config.

**Comment by Pitastic** [comment]
#### zu 1.
Um aus dem Parent eine Funktion eines importierten Moduls zu nutzen könnte man `Parent.os.listdir()` schreiben. Allerdings ist das **nicht pythonic**, weil die Herkunft von os damit von Parent abhängt. Importiert man Parent mit `from Parent import *` ist sogar gar nicht klar, wo `os` herkommt.

Der **pythonic Way** ist den import immer u wiederholen. Folgende Zeilen haben mich bei Stackoverflow beruhigt :grin: 
> Also, in the import_module pseudo-function, if the name has already been imported somewhere, it will be in the global list of all modules (sys.modules), and so will simply be reused. The file won't be opened again, it won't be executed again, the globals in that modules won't get new values again, and so on. Importing the same module into many places is not wasteful or extra work, it is very fast.

(http://stackoverflow.com/a/3895510/2978727)

**Comment by Pitastic** [comment]
### zu 2.
Ich habe das `RollerShutter` Modul angepasst. Eine Lösung mit der ich zufrieden bin, ist der Import aus dem Parentfolder und das hinterlegen einer Methode `log()` die eine Instanz von `Logger` erzeugt und schreibt:
```
from ..services.Logging import Logger
[...]
	def log(self, text, mode="info", ts=False):
		if mode == "error":
			Logger().error(text, ts)
		elif mode == "status":
			Logger().status(text, ts)
		elif mode == "info":
			Logger().info(text, ts)
```

Da ich im vorigen Commit ein bisschen die Struktur angepasst habe, ist dieses Modul (für Rolläden) auch das einzige, der den Import machen muss. Die Methode vererbe ich dann an die speziellen Rolläden.
**Man könnte auch überlegen, noch eine Ebene darüber wie `Actor allgemein` und `Sensor allgemein` zu erstellen.**
Da wäre ich sogar fast für....
