### ISSUE TITLE
Art der Ansteuerung

### ISSUE THREAD

**Issue by Pitastic** [Daumen-Hoch-AG/PiHomie#3]
#### offene Sender (CUL Stick, FS20, GPIO Funksender)

Mit dem CUL Stick eine direkte Verbindung zum entfernten Gerät aufbauen und ggf. Hersteller Gateways immitieren. Für Funksteckdosen ginge das auch über einen Transmitter und der WiringPy Lib: https://www.raspberrypi.org/forums/viewtopic.php?f=32&t=32177
In die Richtung geht auch dieses Tutorial:
http://www.pcwelt.de/ratgeber/Hausautomatisierung_mit_Raspberry_Pi_-_Folge_2-Low-Budget-Smart-Home-Zentrale-8905719.html
- Benötigt extra Hardware (den Stick) und es sind nicht alle Protokolle offen/immitierbar.
- Sollte meiner Meinung der Kernpunkt unseres Projekts sein, um Hersteller unabhängig zu sein
#### Hersteller Gateways einbinden

Die vom Hersteller des Sensors/Aktors vorgesehenen Gateways einbinden um über sie Daten auszulesen und Aktionen zu senden (REST, WebAPI).
Dann müssten wir aber viele verschiedene Gateways unterstützen und das würde entgegen der Vereinfachung sein auf die wir abzielen !
#### Einbinden von anderen Projekten

Es sind ja durchaus schon Projekte vorhanden, die sich dieser Problematik angenommen haben. Wie sinnvoll wäre es einige davon als Modul einzubinden und deren API zu nutzen ? Oder fehlt uns dann die Flexibilität ? z.B.:
- https://pimatic.org/ <br>ist ein node.js Projekt, dass mit seinen Modulen verschiedene Geräte unterstützt und eine API bietet.
- http://fhem.de/fhem.html

Machen wir dann zuwenig selber :question:

**Comment by janleck** [comment]
#### Einfache Funktsteckdosen und Schalter

Diese könnte man z.B. auch sehr einfach über Tinkerforge ansteuern. Hierfür gibt es ein eigenes Bricklet, welches recht umfangreiche Unterstützung bietet.
http://www.tinkerforge.com/de/doc/Hardware/Bricklets/Remote_Switch.html

#### Generelle Unterstützung von Drittsystemen und Bibliotheken

Wenn wir andere Bibliotheken finden die uns gefallen, seh ich da kein Problem diese zu nutzen, wäre ja bei Tingerforge im Prinzip das gleiche. Wie gesagt wir sollten mit ein paar ausgewählten beginnen und dann nach und nach ergänzen.

**Comment by Pitastic** [comment]
#### zWave
- zWave Modul (<a href='https://www.amazon.de/dp/B00IGE38JM/?tag=smart.home-21'>**~55 €**</a>) oder<br>
- zWave USB Dongle (<a href='https://www.amazon.de/Z-Wave-ZME_UZB1-Stick-Windows-Linux/dp/B00QJEY6OC?tag=meintechblog-150914-21'>**~30 €**</a>)

#### Homemtaic
- USB-Funkmodul <a href='https://www.amazon.de/HomeMatic-Funkmodul-für-Raspberry-HM-MOD-RPI-PCB/dp/B01G2FM4F0'>**~30 €**</a>

#### Funk (FS20, MAX! etc.)
- CUL Stick (zusammengebaut, geht günstiger) <a href='http://shop.busware.de/product_info.php?products_id=29'>**~ 50 €**</a> oder
- Remote Switch Bricklet von Tinkerforge (MasterBrick erforderlich) für <a href='http://www.tinkerforge.com/de/doc/Hardware/Bricklets/Remote_Switch.html'>**~17 €**</a>

#### iComfort (REV)

verschlüsselt, nicht offen

#### RWE Smarthome

Geräte von eq3 und Homematic aber wohl mit eigener, verschlüsselter Kommunikation (mit Ausnahme des Rauchmelders <a href=''>wohl</a>. Wenn dem so ist, wäre es eh sinnlos diese und nicht gleich Homematic zu kaufen 😉 

#### EnOcean (PEHA)

...wohl nur für Großkunden wie das aussieht

**Comment by Pitastic** [comment]
Die unterstützten Geräte, Module und ihre Protokolle können wir über das Projects Modul "Hardware" diskutieren.

In Sachen Protokolle sollten wir (weil ich es auch gekauft habe :smirk: ) mit Folgendem starten:
- **zWave**
- **433 MHz Funk**
- **Homematic Funk**

In naher Zukunft wäre dann bald auch schön:
- **Bluetooth**

Welche Geräte wir damit einbinden und ob weitere Protokolle notwendig werden können wir wie gesagt dann immer <a href="https://github.com/Daumen-Hoch-AG/SmartHouse/projects/2">**hier**</a> weiterentwickeln/diskutieren.
