### ISSUE TITLE
Der richtige Projektname

### ISSUE THREAD

**Issue by Pitastic** [Daumen-Hoch-AG/PiHomie#8]
Irgendwas mit Py - für Python
- PyHouse
- PyHome
- MyPyHome
- SmartPyHome
- SmartPy
- Shawn (**S**mart**H**ome-System with **A**utomated and **W**ireless **N**etwork)
- Smash (**S**imply **m**anage **a**ll **s**mart**h**omes)

**Comment by janleck** [comment]
Etwas mit PyPi könnte ich mir auch vorstellen, PyPiHome oder ähnlich...

**Comment by Pitastic** [comment]
https://www.drooms.com/de/blog/die-10-beliebtesten-projektnamen-fuer-datenraeume

Irgendwas müssen wir ja jetzt mal nehmen...

**Comment by Pitastic** [comment]
**PiHomie** 👍

**Comment by Pitastic** [comment]
nach Absprache und langer Atempause geändert...
